name: learn-github-actions
on:
  push:
   branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build a docker image 
        run: docker build -t  test-img:latest  .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish the image in the Dockerhub
        run:  |
          docker tag test-img:latest ${{ secrets.DOCKER_USERNAME }}/test-img:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/test-img:latest
          
           

